### ISSUE TITLE
Alias for classes such as `pygame.Joystick` and `pygame.Sound` (3353)

### ISSUE THREAD

**Issue by GalacticEmperor1** [pygame-community/pygame-ce#1658]
#  **Issue &numero;3353 opened by *[novialriptide](https://github.com/novialriptide)* at 2022-07-30 07:08:18**

Classes like `Joystick`, `Event`, and `Sound` cannot be called like `Rect` and `Surface`. Currently, we have to do something like `pygame.joystick.Joystick` instead of `pygame.Joystick`, while `pygame.rect.Rect` can be called as `pygame.Rect`

It'll be nice if they have an alias consistent with `pygame.Rect` and `pygame.Surface`. The following classes need correction:
```
Joystick
Font
Event
Sound
Channel
Clock
```
<hr>

#  Comments

# # #  **[PurityLake](https://github.com/PurityLake)* commented at 2022-07-30 08:47:39*

I'll do this a little later on today

**Comment by zoldalma999** [comment]
fixed by #1854

**Comment by rethanon** [comment]
@zoldalma999 @PurityLake sorry to drag up an old issue, just curious if it was understood at the time that this was only partially resolved as PR #1854 didn't include adding an alias for `pygame.mixer.Sound`.

**Comment by PurityLake** [comment]
I had thought I added it, I can add it later on today

**Comment by rethanon** [comment]
That would be great thanks, I was just curious as I noticed we have an alias for `pygame.mixer.Channel` -> `pygame.Channel` but we don't have one for `pygame.mixer.Sound`
