### ISSUE TITLE
pygame.midi not accessing devices properly on linux

### ISSUE THREAD

**Issue by JiffyRob** [pygame-community/pygame-ce#2155]
**Environment:**
- **Operating system**: Linux(Debian 11), using ALSA and Pipewire
- **Python version**: 3.9 (I might have tested on 3.11 as well, but I don't remember)
- **SDL version**:  Whatever the PyPI builds of my pygame versions shipped with
- **PyGame version**:  Tested on 1.9.6, 2.0.0, 2.1.0, 2.1.1, 2.1.2, 2.1.3-CE (pygame up through 2.1.2 worked, CE did not) (Also the versions of original pygame were tested, 2.2.0 and 2.3.0, and neither of them worked either)

**Current behavior:**

`pygame.midi.get_count()` will always return 0, even if I have multiple virtual and physical devices connected.

**Expected behavior:**

No errors and it sees my devices.  This is how the versions that "worked" behaved.

**Test code**

```py
import pygame.midi
pygame.midi.init() # causes warning
print(pygame.midi.get_count())
```

**Stack trace/error output/other error logs**

```
ALSA lib conf.c:4555:
(snd_config_update_r) Cannot access file /usr/local/share/alsa/alsa.conf
ALSO lib seq.c:935:
(snd_seq_open_noupdate) Unknown SEQ default
```

**Comment by Starbuck5** [comment]
> (pygame up through 2.1.2 worked, CE did not)

... Because pygame-ce didn't exist in those versions?

So this broke between pygame 2.1.2 and pygame 2.1.3? Well that narrows it down to a 14 month period... Not exactly ideal. What about the pygame 2.1.3 dev releases? dev2,dev4,dev6,dev8.

**Comment by PurityLake** [comment]
I have some time today, I can look into this

**Comment by PurityLake** [comment]
@JiffyRob 

What version of Alsa are you using? Please give me the result of `cat /proc/asound/version`

**Comment by PurityLake** [comment]
ALso since you are running Ubuntu you should reinstall your audio libraries like so:

`sudo apt-get install --reinstall libasound2 libasound2-data libasound2-plugins`

It seems you `alsa.conf` is missing and this should fix it, restart your machine and try pygame-ce again.

**Comment by JiffyRob** [comment]
@PurityLake Thanks for the work, I'll look into that as soon as I have time.  
@Starbuck5 maybe I was unclear - No versions of pygame-ce worked, but pygame versions up to that point did.  At any rate, I'll get to that as well when I have time.  Finals are coming up, so it might be a little bit.

**Comment by JiffyRob** [comment]
@PurityLake the given apt command did not fix the problem.  Output of `cat /proc/asound/version` is `Advanced Linux Sound Architecture Driver Version k5.10.0-22-rt-amd64`

**Comment by JiffyRob** [comment]
@Starbuck5 I only have `dev6` and `dev8` available for my current version of python (3.9).  Both of those showed the bug.  I'll try a couple of other versions floating around on my system and see if those will get closer in.

**Comment by Starbuck5** [comment]
I looked into it and the binary releases of pygame 2.1.3.dev2 and dev4 have been deleted off of pypi. You can still get the releases by navigating to the pygame repo's releases page and downloading the artifacts directly from there.

**Comment by PurityLake** [comment]
@JiffyRob may I ask what midi device you have plugged in? Do you have the correct drivers installed for it? I am seeing no real issues in the pygame code for it as it basically outsources the code to `portmidi`. Unfortunately I don't have a midi keyboard with me for the next while.

**Comment by PurityLake** [comment]
Also what could you post you `alsa.conf`? Use `cat /usr/share/alsa/alsa.conf`

I have a feeling that for some reason ubuntu did not add the file again.

**Comment by JiffyRob** [comment]
@PurityLake Sorry once again for the late reply, the output is very long so I will only post the top:
```
#
#  ALSA library configuration file
#

# pre-load the configuration files

@hooks [
        {
                func load
                files [
```
At any rate, there is stuff in it, so the file is there.
Also for devices I have a Midi Thru on mmy computer that pygame sees when it doesn't err out, as well as a Nektar LX49+ connected via USB.  I presume I have the correct drivers set up for it because I have used it with other programs like LMMS.
