### ISSUE TITLE
Win10 libpng16-16.dll incompatibility - fixed with older DLL

### ISSUE THREAD

**Issue by celeritydesign** [pygame-community/pygame-ce#2650]
Win10 Home Edition
pygame-ce 2.4.0
python  3.11.4
SDL 2.28.5

On an old laptop, I uninstalled pygame 2.5 and replaced with pygame-ce 2.4.0

My program failed to load on this line:

bg = pygame.image.load(img_path + "bg/" + "bg.png").convert() 

Error was a pop up OS window: "Entry point not found - The procedure entry point inflate/validate could not be loated in the dynamic link library [...] libpng16-16.dll"

![libpng](https://github.com/pygame-community/pygame-ce/assets/285563/72420418-ec25-4c2e-bc68-4d8bb6c0f5b2)

The fix was to replace C:\Users<username>\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygame\libpng16-16.dll with an older version packaged with SDL 2.0.1 : SDL2_image-2.0.1-win32-x64.zip

I sourced that package from here: https://www.libsdl.org/projects/SDL_image/release/

Swapping the DLL between the above and the one packaged with pygame-ce replicates the error every time. As noted, pygame 2.5 did not cause the same issue on this laptpop.

Posting here just in case it helps somebody in future.  It seems to be a known issue going back years (obviously not directly related to pygame-ce!)  [ref: https://discourse.libsdl.org/t/sdl2-image-fails-loading-libpng-on-latest-versions-when-cross-compiling/24494 ]

**Comment by oddbookworm** [comment]
You posting your problem and solution here is appreciated! Although, as you pointed out, this isn’t exactly an issue with pygame-ce, so having an open issue about it perpetually might not be the best idea. I’m not closing this issue, but someone else might for that reason (but keep it around for future reference). Although, I think this would be a good thing to add to an FAQ/troubleshooting section in our wiki (with appropriate credit given)

**Comment by ankith26** [comment]
It actually may be an issue with pygame-ce, could you please test if `pygame-ce==2.4.0.dev2` fixes the issue for you?

I'm suspecting the `libpng16-16.dll` we are currently distributing after https://github.com/pygame-community/pygame-ce/pull/2596 came into affect, is not correctly linked against zlib somehow?

**Comment by celeritydesign** [comment]
Indeed! Not a problem at all to close this issue, in fact I expected that.  It will still be easier to search for than on Discord ;)
I suspect this will only affect old Windows machines anyway, but there are bound to be people like me enjoying playing with pygame on an old laptop!

**Comment by celeritydesign** [comment]
2.4.0.dev2 worked fine for me - but 2.4.0 current now works as well(!).
I’ve uninstalled and tested a few times now, and can no longer replicate the error. So I’m a bit confused how I managed to get the problematic libpng-16-16.dll installed last night when I did the same clean install.
Apologies if this has turned out to be a false alarm. I spent ages last night trying to fix as per the original report above!

**Comment by celeritydesign** [comment]
Apologies, previous test was a waste of time - I’d copied the “good” version of libpng16-16.dll to my local game folder so I didn’t lose it, and Python must check there first.
Deleting that file from my project gives the following test results:

2.4.0dev2 - no problems
2.4.0 - same libpng problem

So yes, for my environment, the final release of 2.4.0 does seem to ship with a version of libpng.dll that fails.

**Comment by Starbuck5** [comment]
I’m the one who put in the libpng for the SDL_image change in this release. I used the same build of libpng we were previously using from SDL_image 2.0.5. Maybe zlib problem as Ankith suggested then.

I’m not at my computer at the moment but I’d like to verify it’s actually the same build of libpng.

is there anything weird about your Python? Is it CPython, where did you install it from? 64 bit?

Maybe your system is inserting some incompatible version of zlib somehow?

Maybe some artifact from pygame is persisting.  Have you cleanly uninstalled both pygame and pygame-ce and tried again?

**Comment by oddbookworm** [comment]
I'm not sure if it matters, but are you using the default wayland-over-x11 or did you use raspi-config to switch to X11?

**Comment by ankith26** [comment]
It doesn't matter as OP is on windows and this must be a windows specific thing.

Anyways, this does not seem like a general problem, something about OPs enviroment triggers this issue. I checked one of the windows release wheels, and they have the zlib dll and the libpng dll should be linked against it already.

In addition to what @ Starbuck5 said, maybe also try updating your system if you haven't.

**Comment by Starbuck5** [comment]
I've confirmed that 2.4.0 and 2.4.0.dev2 have the same copy of libpng16-16.dll and zlib1.dll. Verified the hashes of the files.

I found this stackoverflow post where someone had this problem and it was a different copy of zlib on the path mucking things up- https://stackoverflow.com/questions/43735638/execution-impossible-on-w10-with-a-cross-compiled-libpng16-16-dll

Maybe SDL_image 2.8 has a different dynamic loading implementation than SDL_image 2.0.5 and that makes this possible?

We could also try building a new version of libpng ourselves, rather than using the prebuilt we've been using. I thought using the same exact version as before would be the safer (and easier) option ☹️

**Comment by ankith26** [comment]
> Maybe SDL_image 2.8 has a different dynamic loading implementation than SDL_image 2.0.5 and that makes this possible?

SDL_image has primarily two ways of linking with its deps, one is "shared" (basically dlopen-ing the dll of the dep) and the other is regular linking which is what we want to do. This is controlled by compile time flags (atleast on linux).

**Comment by celeritydesign** [comment]
Apologies for the hassle this ticket is causing :-( . It does look like an edge case on my environment, which is a good thing I suppose!

> is there anything weird about your Python? Is it CPython, where did you install it from? 64 bit?
 
There is nothing unusual about it as far as I know. The laptop is nine years old(!) but I've kept python uptodate since using pygame.  Python is running in 64bit mode (I just checked using sys.maxsize ). 
(I did seem to have an old install of python 3.7 kicking around, but it wasn't being used and I uninstalled it today just in case)

> Maybe your system is inserting some incompatible version of zlib somehow?
Do you mean zlib1.dll in the same location as libpng-16-16.dll? See below...

> Maybe some artifact from pygame is persisting. Have you cleanly uninstalled both pygame and pygame-ce and tried again?
So this is the timeline:
- I was using pygame 2.5.0 on this laptop, but with the release of pygame-ce 2.4.0 thought it was a good idea to migrate over
-  I was already using pygame-ce on our Raspberry Pi with it installed via venv, so tried the same on the Windows laptop. That was when I first saw the libpng error.  At this point pygame (non CE) was still installed on the system.
- Thinking it was maybe a venv issue, I deleted all the venv folders and python.cfg in my game root and unistalled pygame, then installed pygame-ce - at this point old pygame was not on my system.
- I had the same libpng problem, which led me to look at C:\Users\<username>\AppData\Local\Programs\Python\Python311\Lib\site-packages\pygame\libpng16-16.dll and that was when I found the fix by copying the SDL 2.0.1 libpng dll.
- I then posted here and did more tests as per above.

Today, I have hashed libpng16-16.dll and zlib1.dll to compare between 2.4.0 and 2.4.0dev2 and I can confirm there is no difference on my machine.  But there is obviously a difference with the libpng DLL from SDL 2.0.1

So, the situation for me, is that I can uninstall pygame-ce and replace with 2.4.0dev2 and my game runs (I can load pngs :-) ). But if I uninstall that and then install 2.4.0 I get the libpng error, and the only fix I know of is to replace the libpng DLL with the one packaged from SDL 2.0.1.
In case it's of any use, I tried fixing using libpng from SDL 2.0.3 and that didn't work, it gave me the same error.

**Comment by Starbuck5** [comment]
Every other format works though, besides PNG? 

Run `python -m pygame.tests.image_test`

**Comment by Starbuck5** [comment]
@celeritydesign I'm pretty confident this will work, but could you test this libpng please.

[libpng16-16.zip](https://github.com/pygame-community/pygame-ce/files/13946721/libpng16-16.zip)

Rather than going older, this goes newer. I built this on my machine using the latest libpng source.

**Comment by celeritydesign** [comment]
@Starbuck5 - that works!

Output from python -m pygame.tests.image_test with previous DLL:

```
Ran 48 tests in 23.769s
FAILED (failures=1, errors=11)

```
Output with your newer DLL:

```
Ran 48 tests in 2.232s

OK
```

**Comment by Starbuck5** [comment]
If you install the wheel from this zip file the issue should be fixed. [pygame-wheels-windows-CPython 3.11 (64 bit).zip](https://github.com/pygame-community/pygame-ce/files/13959376/pygame-wheels-windows-CPython.3.11.64.bit.zip)

Generated from PR #2674 with a new version of SDL_image on Windows with the new libpng.

**Comment by camprevail** [comment]
Hi, I'm having this same issue and have been searching for solutions everywhere. Is zlib supposed to be distributed with pygame-ce? Because I can't find any files matching "zlib" in my site-packages folder. I'm using windows 64bit python 3.12.9 in a virtual environment. I tried installing pygame-ce from pip and from the wheel on github.

**Comment by oddbookworm** [comment]
@camprevail what's the output of `pygame.print_debug_info()`?

**Comment by camprevail** [comment]
```
Platform:		Windows-10-10.0.19045-SP0
System:			Windows
System Version:		10.0.19045
Processor:		Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
Architecture:		Bits: 64bit	Linkage: WindowsPE
Driver:			Display Not Initialized
Python:			CPython
pygame version:		2.4.0
python version:		3.12.9
SDL versions:		Linked: 2.28.5	Compiled: 2.28.5
SDL Mixer versions:	Linked: 2.6.2	Compiled: 2.6.2
SDL Font versions:	Linked: 2.20.2	Compiled: 2.20.2
SDL Image versions:	Linked: 2.8.0	Compiled: 2.8.0
Freetype versions:	Linked: 2.11.1	Compiled: 2.11.1
pygame.print_debug_info()
Platform:		Windows-10-10.0.19045-SP0
System:			Windows
System Version:		10.0.19045
Processor:		Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
Architecture:		Bits: 64bit	Linkage: WindowsPE
Driver:			Display Not Initialized
Python:			CPython
pygame version:		2.4.0
python version:		3.12.9
SDL versions:		Linked: 2.28.5	Compiled: 2.28.5
SDL Mixer versions:	Linked: 2.6.2	Compiled: 2.6.2
SDL Font versions:	Linked: 2.20.2	Compiled: 2.20.2
SDL Image versions:	Linked: 2.8.0	Compiled: 2.8.0
Freetype versions:	Linked: 2.11.1	Compiled: 2.11.1

```

**Comment by camprevail** [comment]
specifically I'm trying to load the blit_blends example and am getting the  `Failed loading libpng16-16.dll: The specified procedure could not be found` error

**Comment by Starbuck5** [comment]
You’re using 2.4.0, this was fixed in 2.4.1.

**Comment by camprevail** [comment]
Ah sorry I switched to an older build to test it and forgot to switch back. Here's the new debug output, still getting the same error.
```
pygame-ce 2.5.3 (SDL 2.30.12, Python 3.12.9)
pygame.print_debug_info()
Platform:		Windows-10-10.0.19045-SP0
System:			Windows
System Version:		10.0.19045
Processor:		Intel64 Family 6 Model 142 Stepping 9, GenuineIntel	SSE2: Yes	AVX2: Yes	NEON: No
Architecture:		Bits: 64bit	Linkage: WindowsPE
Python:			CPython 3.12.9 (tags/v3.12.9:fdb8142, Feb  4 2025, 15:27:58) [MSC v.1942 64 bit (AMD64)]
pygame version:		2.5.3
SDL versions:		Linked: 2.30.12	Compiled: 2.30.12
SDL Mixer versions:	Linked: 2.8.0	Compiled: 2.8.0
SDL Font versions:	Linked: 2.24.0	Compiled: 2.24.0
SDL Image versions:	Linked: 2.9.0	Compiled: 2.9.0
Freetype versions:	Linked: 2.11.1	Compiled: 2.11.1
Display Driver:		Display Not Initialized
Mixer Driver:		Mixer Not Initialized
```

**Comment by camprevail** [comment]
Alright I finally tracked it down to this: it was using my inkscape installation's libpng. It looks like inkscape put itself on the system PATH variable, so once I removed that it worked. I was under the impression that virtual python environments put themselves at the top of the system path though when you activate them, so I'm not sure how it wasn't finding the libpng dll in the venv site-packages folder first.
